### PR TITLE
Use svg deploy with balena button

### PR DESCRIPTION
**Pull request by iamsolankiamit**

### CODE REVIEW

**Comment by shawaj** [comment]
thanks @iamsolankiamit

**Comment by shawaj** [comment]
@iamsolankiamit is the .svg version the suggested one to use now going forward instead of the .png?

**Comment by iamsolankiamit** [comment]
@shawaj yes, svg renders more clear on readmes, png is still there though.

**Comment by shawaj** [comment]
@iamsolankiamit should we update the [balena docs](https://github.com/balena-io/docs/edit/master/pages/learn/deploy/deploy-with-balena-button.md) do you think? Happy to do a PR

**Pull request merged**
